### ISSUE TITLE
Can't install via HACS 1.1.2

### ISSUE THREAD

**Issue by edgimar** [apop880/Night-Mode#3]
Trying to add a custom repository to HACS 1.1.2 with the https://github.com/apop880/Night-Mode URL results in a "Repostitory structure for v1.0.0 is not compliant" error.

**Comment by thisisbenwoo** [comment]
+1

**Comment by thisisbenwoo** [comment]
> +1

Nevermind. User error on my part! Sorry...

**Comment by apop880** [comment]
@edgimar 

Sorry for the delay, working on catching up on old issues. Are you still seeing this? I am able to add via the latest version of HACS.

**Comment by edgimar** [comment]
I am not currently using it, so unfortunately can't confirm whether it works.  Since it seems to work for you, I'll go ahead and close this.
